### PR TITLE
Added new links for meeting recording

### PR DESCRIPTION
**Pull request by namankumar**
Prior location of videos was not publicly shareable. New location is, and so the videos should be viewable on the meetings webpage

### CODE REVIEW

**Comment by namankumar** [comment]
@kalepail @ElliotFriend any idea why the videos are not showing up? The permissions are set to public from what I can tell

Affected meetings: 
https://developers-pr379.previews.kube001.services.stellar-ops.com/meetings/2024/03/14
https://developers-pr379.previews.kube001.services.stellar-ops.com/meetings/2024/02/29

Source dir:
https://drive.google.com/drive/folders/1v7hQpYCe2SqaaJYqllFUlijfuZZ-giT1

**Comment by kalepail** [comment]
Make sure you're getting the embed video link and not just the video link
https://www.colby.edu/acits/2020/01/30/how-to-embed-a-video-from-google-drive/

**Comment by kalepail** [comment]
Made the tweaks. You had the right link, just needed to be `/preview` not `/view`

**Comment by namankumar** [comment]
Awesome thanks!

**Review by kalepail — APPROVED** [review]
lgtm

**Pull request merged**
