### PR TITLE
Add description of nomination leader election algorithm

### PR DESCRIPTION
**Pull request by bboston7**
Part of stellar/stellar-core#4387

This change adds a section to the admin guide explaining the impact of validator quality levels on SCP nomination leader election.

### CODE REVIEW

**Comment by nano-o** [comment]
Are we leaving out "CRITICAL" on purpose? I opened an issue about it yesterday for another part of the docs: https://github.com/stellar/stellar-docs/issues/985

**Comment by briwylde08** [comment]
Couple editorial nits but will defer to @marta-lokhova for content correctness and approval [🙏](https://emojipedia.org/folded-hands)

**Comment by marta-lokhova** [comment]
Thanks for documenting leader election! I have a similar question to @nano-o's - do we want to mention CRITICAL quality as well?

**Comment by bboston7** [comment]
The problem is that there's no mention of CRITICAL anywhere else in the docs, so I think it would be wrong/confusing to mention it only in the nomination leader election section. We could add a description of CRITICAL to the admin docs, but I'm not sure whether CRITICAL was intentionally left out of the docs, which is what I think @nano-o's question is getting at.

**Comment by bboston7** [comment]
After some discussion with @marta-lokhova we decided to add a generic, level-agnostic description of the algorithm, as well as an example using HIGH, MEDIUM, and LOW quality validators. I'll make that change and ping @marta-lokhova when it's ready.

**Comment by bboston7** [comment]
> we decided to add a generic, level-agnostic description of the algorithm, as well as an example using HIGH, MEDIUM, and LOW quality validators.

I just pushed up a change that accomplishes this, and rebased on `main`. @marta-lokhova, this is ready for another round of review when you have a moment!

**Review by marta-lokhova — APPROVED** [review]

**Pull request merged**
