### PR TITLE
Resolves Docs Bounty Issue 335

### PR DESCRIPTION
**Pull request by rahul-soshte**
In this PR, I have added example for a fee bump tx as the issue suggested. Resolves [#335](https://github.com/stellar/stellar-docs/issues/335)

### CODE REVIEW

**Comment by rahul-soshte** [comment]
@briwylde08 This PR is ready for review

**Review by ElliotFriend — COMMENTED** [review]
Hi, @rahul-soshte!! This is an excellent addition! Thank you!!

The only thing you'll need to add is an import for the `<CodeExample>` component. You can add this at the top of the file, right below all the "frontmatter" (the block with the page title and sidebar position stuff):

```mdx
import { CodeExample } from "@site/src/components/CodeExample";
```

**Comment by rahul-soshte** [comment]
Yes, @ElliotFriend I have added that import now

**Review by ElliotFriend — APPROVED** [review]
Thanks so much @rahul-soshte! Great addition!

**Comment by briwylde08** [comment]
Thank you @rahul-soshte! We'll continue the conversation in the corresponding issue.

**Pull request merged**
