### PR TITLE
Update README.mdx

### PR DESCRIPTION
**Pull request by kushagra2jindal**
This is important to register the account, or else the server.loadAccount will give an error, creating confusion for the new developers.

### CODE REVIEW

**Comment by ElliotFriend** [comment]
Hi, @kushagra2jindal! Thanks so much for the PR!

You bring up a good point about the accounts in the example being unfunded. I don't know that we really want to get into the weeds of all that here, though. This "quickstart" is more meant as an illustration, rather than a copy/paste snippet. It feels like Friendbot stuff could be left as an exercise for the reader?

Maybe we could have a comment pointing to our [create an account tutorial](https://developers.stellar.org/docs/tutorials/create-account#create-account) after the two keypairs are declared? something like:

```js
const issuerKeypair = Keypair.random();
const destinationKeypair = Keypair.random();
// Don't forget to fund these accounts, somehow. Have you met Friendbot?
// https://developers.stellar.org/docs/tutorials/create-account#create-account
```

What do you think?

**Comment by kushagra2jindal** [comment]
Hi, @ElliotFriend adding the comments will solve the problem. Thanks!

**Comment by briwylde08** [comment]
Hi @kushagra2jindal! Are you able to make the suggested edit? Thank you!

**Review by briwylde08 — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
