### PR TITLE
A couple small updates

### PR DESCRIPTION
**Pull request by silence48**
Everywhere else that an 'encyclopedia' entry is referenced, it is a link. this updates the 'error handling encyclopedia' reference to also be a link.

### CODE REVIEW

**Comment by silence48** [comment]
I also added a link to the discord server in the validators section, adjacent to the keybase invite, since discord is used more than keybase now.

**Comment by silence48** [comment]
I also added a code example for creating an account with stellar-sdk programmatically from a funded account, as the only current example was using friendbot.  I think having the actual create account op demonstrated is important also.

**Comment by silence48** [comment]
I'm having some errors with the github actions concerning 2 files I didn't touch? 

[warn] jsxBracketSameLine is deprecated.
[warn] docs/fundamentals-and-concepts/stellar-data-structures/assets.mdx
[warn] docs/tutorials/moneygram-access-integration-guide.mdx

I did add a js code example but it wasn't in those files. 

if there's something I need to fix lmk.

**Comment by briwylde08** [comment]
Thanks, silence! 

@tyvdh or @ElliotFriend can you check the code on this one?

**Comment by silence48** [comment]
> Thanks, silence!
> 
> @tyvdh or @ElliotFriend can you check the code on this one?
sorry added one more commit to fix the github actions issues.  mdx:check will pass now but there is still a warn about the deprecated option related to https://github.com/stellar/product-conventions/issues/43

**Pull request merged**
