### PR TITLE
add link for fee simulation tool to developer tools

### LINKED ISSUE #598: Build a GUI tool for fee simulation
**Get awarded:** up to $750 worth of XLM
**Section:** Tools - Developer Tools: https://github.com/stellar/stellar-docs/blob/main/docs/tools/developer-tools.mdx - link to the tool in this section, feel free to post a link to the tool in this issue as well

**The GUI could include the following features:**

- Fee estimation - enable users to estimate fees based on current network conditions
- Fee simulation - allow users to simulate transactions with different fee settings to find optimal costs
- Fee history tracking - display historical fee data and trends

### PR DESCRIPTION
**Pull request by Myestery**
fixes #598

### CODE REVIEW

**Comment by Myestery** [comment]
@briwylde08 This is ready for review

**Comment by briwylde08** [comment]
Thank you @Myestery! We'll get this reviewed and provide feedback in the next couple of weeks!

**Comment by janewang** [comment]
@Myestery Is this estimation just the resources fees or inclusion fees? We have a new API endpoint that gives the real time inclusion fees for soroban and stellar transactions.

```
curl -X POST \
-H 'Content-Type: application/json' \
-d '{
  "jsonrpc": "2.0",
  "id": 8675309,
  "method": "getFeeStats"
}' \
https://soroban-testnet.stellar.org:443 | jq
```

**Comment by Myestery** [comment]
Hello @janewang 

> @Myestery Is this estimation just the resources fees or inclusion fees? We have a new API endpoint that gives the real time inclusion fees for soroban and stellar transactions.
> 
> ```
> curl -X POST \
> -H 'Content-Type: application/json' \
> -d '{
>   "jsonrpc": "2.0",
>   "id": 8675309,
>   "method": "getFeeStats"
> }' \
> https://soroban-testnet.stellar.org:443 | jq
> ```

Hi @janewang 
The RPC method getStats was not working at the time I did this on the soroban testnet
It only worked on horizon

**Comment by Myestery** [comment]
Screenshot 2024-07-12 at 16 56 52
The application shows resource as well as inclusion fees

**Comment by Myestery** [comment]
> @Myestery Is this estimation just the resources fees or inclusion fees? We have a new API endpoint that gives the real time inclusion fees for soroban and stellar transactions.
> 
> ```
> curl -X POST \
> -H 'Content-Type: application/json' \
> -d '{
>   "jsonrpc": "2.0",
>   "id": 8675309,
>   "method": "getFeeStats"
> }' \
> https://soroban-testnet.stellar.org:443 | jq
> ```

I have updated the RPC estimation endpoint from horizon to soroban using this new API

**Comment by Myestery** [comment]
Hi @kalepail 
THis is waiting for your review please

**Comment by briwylde08** [comment]
Hi @Myestery, 

Thank you so much again for your submissions. Please see my comment on this PR: https://github.com/stellar/stellar-docs/pull/736 for more general feedback.

@kalepail had the following feedback and reasoning specifically for this PR as to why we can't currently accept this submission:

- The tool is currently configured exclusively for use with Testnet, limiting its application in a production environment
- The simulation contract is embedded within the code, restricting flexibility for users who may wish to test different contracts
- The tool offers limited customization options, serving primarily as a basic interface for the simulation endpoint, without allowing for modifications or extensions
- Other tools within the suite similarly function mainly as interfaces for underlying tools

**Comment by CaptainPrinz** [comment]
@briwylde08  if this is till available I would like to work on it

**Comment by briwylde08** [comment]
Closing per feedback above.

**Pull request closed without merging**
