### PR TITLE
Added "Security Tools" category and "Scout: Bug Fighter" entry

### PR DESCRIPTION
**Pull request by matiascabello**
This PR adds the "Security Tools" category to the "Developer Tools" documentation, with "Scout: Bug Fighter" as the first entry in this new category.

Scout is a static code analysis tool designed to assist Soroban developers and auditors in identifying potential security threats, with a strong focus on detection capabilities, usability, and developer experience.

**Maintainability**

Scout is under active development and has continuous support. Since its launch in June 2023, 17 versions have been released, three of them in the past 30 days. The most recent release (0.2.15) has been downloaded 264 times from the crates.io Rust package manager. The total number of downloads since Scout's launch has reached over 7,000. See Scout crates.io entry [here](https://crates.io/crates/cargo-scout-audit).

**Functionality**

Scout analyzes Soroban smart contracts to identify potential issues and deviations from best practices, helping developers write safer and more reliable code. Please refer to [this video](https://www.youtube.com/watch?v=L4kGwPDuWgA) for a quick introduction.

It currently supports 23 detectors, with 4 additional detectors to be released shortly.

The tool includes various features to facilitate smooth integration into developers' workflows:

- A CLI to run Scout directly from the terminal.
- A [VSCode extension](https://marketplace.visualstudio.com/items?itemName=CoinFabrik.scout-audit) for integration into one of the most popular IDEs.
- A [GitHub action](https://github.com/CoinFabrik/scout-actions) for integration into CI/CD pipelines.
- Multiple output formats (md, pdf, json, html, sarif).

**Documentation**

Scout includes comprehensive documentation on detectors and tool usage, available [here](https://coinfabrik.github.io/scout-soroban/docs/intro).

**Community Support**

Scout has been awarded in 3 Stellar Community Fund submissions, and the Scout team remains active in Soroban's developer community.

In addition, we have ongoing initiatives to contribute to the community with educational material on security and Soroban development:

- Workshops
- [Video tutorials](https://www.youtube.com/playlist?list=PLmy8sJH8bR7L_k6-5Ou2eoLuJ3yE7qTAu)
- [Security-reviewed Soroban smart contract examples](https://github.com/CoinFabrik/scout-soroban-examples)

Scout website: [https://www.coinfabrik.com/products/scout/](https://www.coinfabrik.com/products/scout/)  
Scout repository: [https://github.com/CoinFabrik/scout-soroban](https://github.com/CoinFabrik/scout-soroban)

### CODE REVIEW

**Comment by briwylde08** [comment]
Thank you so much for the PR! We'll get it reviewed and approve or let you know if we have any feedback [🙏](https://emojipedia.org/folded-hands)

**Comment by briwylde08** [comment]
Hi! Sorry for the delay on reviewing this. It's on our radar and we'll get to it soon.

**Comment by matiascabello** [comment]
> Hi! Sorry for the delay on reviewing this. It's on our radar and we'll get to it soon.

No problem! Let me know if you need any further clarifications.

**Comment by anataliocs** [comment]
This is actually really awesome.  The reports, especially the HTML format, is really clear and easy to use and has a lot of great context for how to resolve the issue.

image

**Comment by anataliocs** [comment]
The VS code extension is great too, identifying security issues early in the dev process.

image

**Review by anataliocs — APPROVED** [review]
@briwylde08 @ElliotFriend @carstenjacobsen This is actually a really cool dev tool.

The VSCode plugin identifies security vulnerabilities directly in the IDE with really rich hover text context.

The output reports are really detailed too and give context to the dev about how to resolve the vulnerability.

I would go farther and say we should recommend this dev tool as a best practice.

I would just be curious how @matiascabello maintains the detectors and vulnerability library in terms of keeping it up-to-date with new Soroban releases.

Def 👍 up for me to 🚢 .  See prior comments for verification of functionality

**Comment by briwylde08** [comment]
Great feedback! Thank you @anataliocs! @ElliotFriend I'm happy to merge if you are.

**Comment by ElliotFriend** [comment]
Love to hear it! Thanks @anataliocs for testing and vetting it!! 👍🏻

**Comment by briwylde08** [comment]
Alright, thanks again @matiascabello!

**Pull request merged**
