### PR TITLE
Fixes Deep Dive Docs Bounty Issue 598

### PR DESCRIPTION
**Pull request by rahul-soshte**
Added a new category called Network Insights, in the Developer Tools, and added the link to the fee simulator tool, along with a nice description
Resolves issue #598

### CODE REVIEW

**Comment by briwylde08** [comment]
Awesome work! We'll get this assigned and reviewed [🎉](https://emojipedia.org/party-popper)

**Comment by sisuresh** [comment]
Hey @rahul-soshte, thanks for contributing. Some feedback and a request - Under estimation with Write Ledger Entries set to 5, it returns 5 xlm. It looks like the values make more sense once they're all filled in. The estimation tab is also missing parameters for rent. 

Can you please demonstrate the calculations are right by making sure the result from Simulation matches up with what Estimation returns? I found a transaction on [testnet](https://stellar.expert/explorer/testnet/tx/3ef793ad7653c371e590cba4b1ab823eaf1b7aed60fab2295b27dd550cd9d922), put it into simulation, and then put those values into Estimation, which returned a lower value (I'm guessing because the rent calculation was missing). Another thing to look into - the writeBytes shown on stellar.expert for the transaction I linked when you expand the arrows on the right is 3x higher than what your Simulation returns. I'm not sure why they're so different.

**Comment by rahul-soshte** [comment]
Thank you @sisuresh for the feedback, I will dig more deep with the calculations and check what's missing in the overall calculations.

**Comment by sisuresh** [comment]
I'd also recommend taking a look at https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/fees.rs.

**Comment by rahul-soshte** [comment]
Hi @sisuresh,

So I have researched the [link](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/fees.rs) that you gave, read the fee docs again, making sure what I am interpreting is correct. I have even open sourced the GUI [repo](https://github.com/rahul-soshte/fee-simulator/tree/master)(actually used the laboratory frontend code as a base), so it is much more faster to get feedback. Here are the changes/clarifications since the last time we talked,

1. I am sending the [writeBytes()](https://github.com/rahul-soshte/fee-simulator/blob/0ad4b2ce2bda37fd490c25b1a5ddcef9365ce802/src/app/(sidebar)/simulate/fees/page.tsx#L285) from what I get from the the simulation properly [here](https://feesimulator.vercel.app/simulate/fees?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;&xdr$blob=AAAAAgAAAACWDRNrgN4HpWfA2B7H3QSMtt7GSK//J3//cH+i//Waf406QExLQAAAAL7AABAZwAAAAEAAAAAAAAAAAAAAABmtQMYAAAAAAAAAAEAAAABAAAAAJYNE2uA3gelZ8DYHsfdBIy23sZIr8nf9wf6L9Zp//jTpAAAAGAAAAAAAAAABKrf0Z9GS//LKu+hOOCq4fWWIWaS1ePWMaLC7oHiY6uD8AAAAJc2V0X3ByaWNlAAAAAAAAAgAAABAAAAABAAAABwAAAAoAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAEBrNWXoAAAAKAAAAAAAAAAAAAFsFmk6VOQAAAAoAAAAAAAAAAAAABC7JTh37AAAACgAAAAAAAAAAAAAAVjr7wbwAAAAKAAAAAAAAAAAAAAARbJhDMgAAAAoAAAAAAAAAAAAAYgjQpjcUAAAABQAAAZEzE3mAAAAAAQAAAAAAAAAAAAAAASq39GfRkvyyrvoTjgquH1liFmktXj1jGiwu6B4mOrg//AAAACXNldF9wcmljZQAAAAAAAAIAAAAQAAAAAQAAAAcAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAABAazVl6AAAACgAAAAAAAAAAAABbBZpOlTkAAAAKAAAAAAAAAAAAAAQuyU4d+wAAAAoAAAAAAAAAAAAAAFY6+8G8AAAACgAAAAAAAAAAAAAAEWyYQzIAAAAKAAAAAAAAAAAAAGII0KY3FAAAAAUAAAGRMxN5gAAAAAAAAAABAAAAAAAAAAEAAAAH34iCDiMa2PMCeHHl3Tz0VJHXt3NeeFcxRmv8KUYAhggAAAAHAAAABgAAAAEqt//Rn0ZL8sq76E44Krh9ZYhZpLV49YxosLugeJjq4PwAAAAkAAAGRMxN5gAAAAAAAAAABAAAAAAAAAAYAAAABKrf0Z9GS//LKu+hOOCq4fWWIWaS1ePWMaLC7oHiY6uD8AAAAJAAABkTMTeYAAAAAAAAAAAgAAAAAAAAAGAAAAASq39GfRkvyyrvoTjgquH1liFmktXj1jGiwu6B4mOrg//AAAACQAAAZEzE3mAAAAAAAAAAAMAAAAAAAAABgAAAAEqt//Rn0ZL8sq76E44Krh9ZYhZpLV49YxosLugeJjq4PwAAAAkAAAGRMxN5gAAAAAAAAAAEAAAAAAAAAAYAAAABKrf0Z9GS//LKu+hOOCq4fWWIWaS1ePWMaLC7oHiY6uD8AAAAJAAABkTMTeYAAAAAAAAAABQAAAAAAAAAGAAAAASq39GfRkvyyrvoTjgquH1liFmktXj1jGiwu6B4mOrg//AAAACQAAAZEzE3mAAAAAAAAAAAYAAAAAAAAABgAAAAEqt//Rn0ZL8sq76E44Krh9ZYhZpLV49YxosLugeJjq4PwAAABQAAAABAIlUQAAAnEAAAAu4AAAAAACYloAAAAABzKXZYAAAAEACmqRBpXbFU8qKDK5RblnLKbH5D5r0y1D8YdbuwHxFfP8cjzI7MqatezfTpaVCOxgjCINZk0JMk5bZjdHG6iAM;;)(used the XDR for the [testnet ](https://stellar.expert/explorer/testnet/tx/3ef793ad7653c371e590cba4b1ab823eaf1b7aed60fab2295b27dd550cd9d922)transaction that you sent), might have been some bug in the stellar.expert

2. What I am showing in the simulate fees [route](https://feesimulator.vercel.app/simulate/fees?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;&xdr$blob=AAAAAgAAAACWDRNrgN4HpWfA2B7H3QSMtt7GSK//J3//cH+i//Waf406QExLQAAAAL7AABAZwAAAAEAAAAAAAAAAAAAAABmtQMYAAAAAAAAAAEAAAABAAAAAJYNE2uA3gelZ8DYHsfdBIy23sZIr8nf9wf6L9Zp//jTpAAAAGAAAAAAAAAABKrf0Z9GS//LKu+hOOCq4fWWIWaS1ePWMaLC7oHiY6uD8AAAAJc2V0X3ByaWNlAAAAAAAAAgAAABAAAAABAAAABwAAAAoAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAEBrNWXoAAAAKAAAAAAAAAAAAAFsFmk6VOQAAAAoAAAAAAAAAAAAABC7JTh37AAAACgAAAAAAAAAAAAAAVjr7wbwAAAAKAAAAAAAAAAAAAAARbJhDMgAAAAoAAAAAAAAAAAAAYgjQpjcUAAAABQAAAZEzE3mAAAAAAQAAAAAAAAAAAAAAASq39GfRkvyyrvoTjgquH1liFmktXj1jGiwu6B4mOrg//AAAACXNldF9wcmljZQAAAAAAAAIAAAAQAAAAAQAAAAcAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAABAazVl6AAAACgAAAAAAAAAAAABbBZpOlTkAAAAKAAAAAAAAAAAAAAQuyU4d+wAAAAoAAAAAAAAAAAAAAFY6+8G8AAAACgAAAAAAAAAAAAAAEWyYQzIAAAAKAAAAAAAAAAAAAGII0KY3FAAAAAUAAAGRMxN5gAAAAAAAAAABAAAAAAAAAAEAAAAH34iCDiMa2PMCeHHl3Tz0VJHXt3NeeFcxRmv8KUYAhggAAAAHAAAABgAAAAEqt//Rn0ZL8sq76E44Krh9ZYhZpLV49YxosLugeJjq4PwAAAAkAAAGRMxN5gAAAAAAAAAABAAAAAAAAAAYAAAABKrf0Z9GS//LKu+hOOCq4fWWIWaS1ePWMaLC7oHiY6uD8AAAAJAAABkTMTeYAAAAAAAAAAAgAAAAAAAAAGAAAAASq39GfRkvyyrvoTjgquH1liFmktXj1jGiwu6B4mOrg//AAAACQAAAZEzE3mAAAAAAAAAAAMAAAAAAAAABgAAAAEqt//Rn0ZL8sq76E44Krh9ZYhZpLV49YxosLugeJjq4PwAAAAkAAAGRMxN5gAAAAAAAAAAEAAAAAAAAAAYAAAABKrf0Z9GS//LKu+hOOCq4fWWIWaS1ePWMaLC7oHiY6uD8AAAAJAAABkTMTeYAAAAAAAAAABQAAAAAAAAAGAAAAASq39GfRkvyyrvoTjgquH1liFmktXj1jGiwu6B4mOrg//AAAACQAAAZEzE3mAAAAAAAAAAAYAAAAAAAAABgAAAAEqt//Rn0ZL8sq76E44Krh9ZYhZpLV49YxosLugeJjq4PwAAABQAAAABAIlUQAAAnEAAAAu4AAAAAACYloAAAAABzKXZYAAAAEACmqRBpXbFU8qKDK5RblnLKbH5D5r0y1D8YdbuwHxFfP8cjzI7MqatezfTpaVCOxgjCINZk0JMk5bZjdHG6iAM;;) is the [max resource fee](https://github.com/rahul-soshte/fee-simulator/blob/0ad4b2ce2bda37fd490c25b1a5ddcef9365ce802/src/app/(sidebar)/simulate/fees/page.tsx#L102). Do I need to add the actual estimate here as well?

3. For the [testnet tx](https://stellar.expert/explorer/testnet/tx/3ef793ad7653c371e590cba4b1ab823eaf1b7aed60fab2295b27dd550cd9d922) that you sent, I am getting the fees bit close to the actual fee charged in the estimation. The actual fee charged was 
0.0357842 but I am getting around, 0.0319042, so I am close but don't know what mistake I am making

4. In the rent calculation form, I am provided for a setting of the current ledger, and also you can add a ledger entry based on the following parameters of a ledger entry,
1. Persistent or Temporary
2. Old Size and New Size
3. Old Live Until Ledger, New Live Until Ledger.
I am sending this data in the fee simulation as well.


5. Please do tell me what more mistakes I might be making as there are some nuances still involved here, which I am missing, or I might be making 1-2 small mistakes, which get the estimation slightly off.
[Rent Estimation GUI Code](https://github.com/rahul-soshte/fee-simulator/blob/master/src/app/(sidebar)/estimate/fees/components/Rent.tsx)
[Other Resource Parameters Estimation GUI Code](https://github.com/rahul-soshte/fee-simulator/blob/master/src/app/(sidebar)/estimate/fees/components/Params.tsx)
[Simulation GUI code](https://github.com/rahul-soshte/fee-simulator/blob/master/src/app/(sidebar)/simulate/fees/page.tsx)

@briwylde08 I am working on this tirelessly, it's just that there are lot many nuances than I thought. I am committed to completing this, and later extending it's scope so that it can be a good SCF project and also for maintenance of the GUI app, ad infinitum, since as Stellar grows, this GUI will need tweaks as well, based on the protocol changes.

**Comment by briwylde08** [comment]
Hi @rahul-soshte! I completely respect that this is not an easy task and appreciate your continued work on it - a tool like this is super valuable to the ecosystem. I have no issues with this qualifying for the bounty (probably worth more than originally posted) and I agree that it would also make an awesome SCF project. I tagged @sisuresh for review again and the team will be in touch with feedback! Thanks again for your work!

**Comment by sisuresh** [comment]
Hey @rahul-soshte, thanks for the improvements. I put the testnet tx into Simulation, which returned the following - 

```
"Fees":
{
"Max Resource fee (XLM)":
0.0372393,
"Max Estimated Fee (XLM)":
"0.0372493",
},
```

but Estimation returned 0.0293787 XLM. Do you know why there's a difference? Is that expected? I'm using 1398989 as the current ledger for both.

**Comment by rahul-soshte** [comment]
Hey @sisuresh Sorry for the delay got caught up in travelling somewhere and fell sick a bit.

So yeah I mean initially in the simulation, I was showing the max fee that simulation Endpoint returned instead of the actual estimated fee, which is wrong and confusing UX. So I now have fixed it. The simulation's estimated fee should match the direct estimation considering all the resource + rent value in the UI.

If you can find more bugs please do let me know. The Testnet tx we were using, has been wiped up by the network reset.

**Comment by rahul-soshte** [comment]
I will have to read these CAP docs on fees, they could help me in making this fee estimator the most perfect and will have esoteric knowledge that isn't available in the stellar docs
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-07.md
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-08.md
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-09.md
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-10.md

**Comment by sisuresh** [comment]
> https://stellar.expert/explorer/testnet/tx/9947144265728

Hey Rahul, sorry for the delayed review. I wouldn't be surprised if users (or maybe even simulation) just adds a buffer for max fee to make sure their transaction will make it into the ledger, so I wouldn't worry about that (still worth looking into though as I bet it'll be educational!). I put a transaction from testnet into your Simulation tab and then into Estimation. The Estimate Total Fee matched between the two, so I think we're good there. The Analytics tab seems broken though. When I'm on the testnet option I see this under Analytics - 
```
Fee Analytics (Mainnet)
Failed to fetch fee data for last 30 ledgers.
```

**Comment by rahul-soshte** [comment]
Hello @sisuresh,

Sorry for the late reply. I am trying to use this project https://www.mercurydata.app/
It was working earlier with an example indexing deployed on [zephyr](https://www.mercurydata.app/), https://github.com/rahul-soshte/soroban-rough-work/blob/master/zephyr-fee-agg-imp/src/lib.rs

Zephyr is a great solution, but its like really new and things are breaking. Now I am getting error while fetching, earlier I was not getting errors while pulling data from a [serverless function](https://docs.mercurydata.app/zephyr-full-customization/learn/custom-apis-serverless-functions), which is written [here in the deployed program](https://github.com/rahul-soshte/soroban-rough-work/blob/e0bb57d877e2bd142487d044531c361c1e4b5bf8/zephyr-fee-agg-imp/src/lib.rs#L131)

I am trying to pull the data from the serverless function [here](https://github.com/rahul-soshte/fee-simulator/blob/8d4c09233ef76d8bfcc0f06a34edd8ec4bc9f658/src/app/(sidebar)/analytics/fees/page.tsx#L33), in the simulator's frontend

I have commented out the analytics part. I wanted to do more work on the analytics part, since it was a interesting topic. I had also applied for a SCF Build Award for this, but got rejected on that. Now got to form my own budget, and wait for the Zephyr ecosystem to mature more for the analytics part.

**Comment by briwylde08** [comment]
Hi @rahul-soshte! Would just like to let you know that @sisuresh is out of office currently but will respond when he gets back!

**Comment by rahul-soshte** [comment]
Okay @briwylde08 thanks for letting me know.

**Comment by sisuresh** [comment]
Hi @rahul-soshte, looks like this is in a good initial state to me. I'll pass the review onto @briwylde08 now. Thanks!

**Comment by briwylde08** [comment]
Thanks @sisuresh for the review and @rahul-soshte on the work! I'm going have one of our devs on DevRel give this a final pass before approval.

**Comment by briwylde08** [comment]
Hi @rahul-soshte! Just sent you a quick email using the address you provided in previous submissions. [🙏](https://emojipedia.org/folded-hands)

**Comment by rahul-soshte** [comment]
Hi @briwylde08 Added the custom domain to the description of the tool. Mailed you as well regarding the same.

**Comment by briwylde08** [comment]
Hi @rahul-soshte! Thanks again for your hard work on this. I'll get this merged and we can take the award conversation to the corresponding issue. Thank you again!

**Review by briwylde08 — APPROVED** [review]

**Pull request merged**
