### PR TITLE
[Soroban Merge] Dapps Challenge

### PR DESCRIPTION
**Pull request by ElliotFriend**
This will migrate the section from the `/dapps` directory on the soroban-docs site into the current site structure.

Refs: stellar/soroban-docs#740, stellar/soroban-docs#781

### CODE REVIEW

**Comment by briwylde08** [comment]
Would it make sense to link to the Freighter wallet How-To Guide from the Introduction? Since you need to connect your wallet to play the challenges?

**Comment by ElliotFriend** [comment]
@briwylde08 great idea!! I added the link [in this commit](https://github.com/stellar/stellar-docs/pull/497/commits/6affddea081459e8b9228d88d1424f0c3cb05837).

Does that feel conspicuous enough, or should it be more "in your face" for people to see?

**Comment by briwylde08** [comment]
Yeah I think that works!!

**Review by Julian-dev28 — APPROVED** [review]
Added some name changes

LGTM!!!

**Pull request merged**
