### PR TITLE
Automatically generate stellar-cli help page.

### PR DESCRIPTION
**Pull request by fnando**
Here's a screenshot of what it looks like:

CleanShot 2024-07-04 at 19 22 06

Here's the preview link: https://developers-pr755.previews.kube001.services.stellar-ops.com/docs/build/smart-contracts/stellar-cli

### CODE REVIEW

**Review by chadoh — APPROVED** [review]
Looks great!

**Comment by chadoh** [comment]
The lack of indentation in the sidebar is a bummer; I've created https://github.com/ConnorGray/clap-markdown/issues/31 to address it. I see you also created https://github.com/ConnorGray/clap-markdown/issues/30, @fnando — I vote we add these issues to our own project board so we can ensure they get done quickly, @janewang.

**Comment by briwylde08** [comment]
Location suggestion: Can we pull this out into its own section, so it would go: 

Tools Overview
SDKs
Developer Tools
Stellar CLI Manual 

And then rename it to the Stellar CLI Manual so it's shorter? LMK what you think!

**Comment by fnando** [comment]
@briwylde08 great suggestion! The new title is way nicer!

CleanShot 2024-07-10 at 10 38 02@2x

**Review by janewang — APPROVED** [review]

**Pull request merged**
