### PR TITLE
doc: guide for extending a deployed contract's Wasm code TTL

### LINKED ISSUE #618: Create a guide for extending a deployed contract’s Wasm code TTL with code
**Get awarded:** up to $150 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

### PR DESCRIPTION
**Pull request by Gift-Naomi**
resolves #618

### CODE REVIEW

**Comment by briwylde08** [comment]
Thank you for your submission! We'll get this assigned and reviewed and let you know any feedback!

**Comment by Gift-Naomi** [comment]
@briwylde08 Alright, I will be waiting.

**Comment by ElliotFriend** [comment]
Hi, @Gift-Naomi! Thanks for participating in our docs bounty!

I'm a little unsure how to start reviewing your contribution. There's a few things you'll need to address before we really can get into reviewing this.

1. You're _replaced_ this [existing guide](https://developers.stellar.org/docs/build/guides/cli/extend-contract-wasm), but we're looking to have a _new_ guide created instead. Probably a new file in the `/docs/build/guides/archival` directory would fit best.
2. It looks like you're writing in a way that could generically apply to several blockchains. I see references to substrate, polkadot, ink, etc. but no mention of Stellar and/or Soroban. We're wanting these guides to be written in a that's targeted and specific to Stellar.
3. Based on the example contract you've provided here, it seems like you might be misunderstanding some of what we mean when we say TTL. Check out the [State Archival docs](https://developers.stellar.org/docs/learn/encyclopedia/storage/state-archival) to get a better handle on it. Particularly, the [terms and semantics section](https://developers.stellar.org/docs/learn/encyclopedia/storage/state-archival#terms-and-semantics) might be useful for a quick overview.

Do those points make sense? If you have any questions, I'm more than happy to help get things unblocked for you.

Thanks again!

**Comment by Gift-Naomi** [comment]
@ElliotFriend 
This guide includes both a code walkthrough and written explanations to help users understand how to extend the TTL of a deployed Wasm contract on Stellar. Let me know if you need any adjustments!

**Comment by Myestery** [comment]
@Gift-Naomi please take a look at https://github.com/stellar/soroban-examples/tree/main/ttl/src
TTL logic is exemplified there

**Comment by Myestery** [comment]
Here too
https://developers.stellar.org/docs/build/guides/archival/test-ttl-extension

**Comment by briwylde08** [comment]
Hi there @Gift-Naomi - we appreciate your effort and participation in the bounty. However, this doesn't quite solve for the ask in the corresponding bounty issue. We are looking for code examples for the task instead of CLI work and the contract code provided in this PR doesn't extend the contract's TTL. Again, we do appreciate the time and effort put into the bounty. If you have any questions, don't hesitate to ask. 

All the best,
Bri

**Pull request closed without merging**
