### PR TITLE
[WIP] Update RPC OpenRPC spec

### PR DESCRIPTION
**Pull request by aditya1702**

### CODE REVIEW

**Comment by 2opremio** [comment]
Really Nice!

**Review by 2opremio — APPROVED** [review]

**Comment by briwylde08** [comment]
Hello! Is this PR still a WIP? Or are we ready to merge? @aditya1702

**Comment by ElliotFriend** [comment]
@aditya1702 if you want to take a crack at moving the changes into that directory, [`/openrpc/README.md`](https://github.com/stellar/stellar-docs/blob/main/openrpc/README.md) can help with some guidance and tips.

On the other hand, if you want, I can help migrate the changes into those files. I know it's a tricky setup, and I'd hate for you to have to duplicate the work

**Comment by aditya1702** [comment]
> Hello! Is this PR still a WIP? Or are we ready to merge? @aditya1702

@briwylde08 Actually we do want these changes to go in. However, we had to revert these changes temporarily in rpc for the current release. So it makes more sense to do them in the next one when they actually go through. I will close this PR for now and create a new one then

**Pull request closed without merging**
