### PR TITLE
Update rpc-providers.mdx

### PR DESCRIPTION
**Pull request by Roman-Liquify**
Liquify here, we've received the grant for running Stellar RPC public infra, would be great to add us to the partners page with links to endpoints available for community.

Info added accordingly to the table but feel free to format it in the better way or list below as public endpoints. Thank you.

### CODE REVIEW

**Review by ElliotFriend — APPROVED** [review]
Hi, @Roman-Liquify! Super-glad to have you on-board! Thanks for sharing!

**Comment by Roman-Liquify** [comment]
Hey @ElliotFriend ! Thank you for confirming! I don't see the info on the main docs page: https://developers.stellar.org/docs/data/rpc/rpc-providers#ecosystem-providers

can you double check please?

**Comment by briwylde08** [comment]
Hi @Roman-Liquify! It can take several minutes for the content to show up after a merge. I see Liquify there now!

**Comment by mollykarcher** [comment]
> However, I am getting errors when clicking the links for Futurenet, Testnet, and Mainnet. Are there other links we can put there?

This is expected as RPC doesn't actually serve any response at it's root url in the same way that Horizon does. You'll probably notice the same issue for the SDF links in the below table. I sanity-checked the health endpoint for each of these and they do indeed work. For example:

```
$ ~  > curl -X POST 'https://stellar.liquify.com/api=41EEWAH79Y5OCGI7/testnet:443/' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "id": 10235,
  "method": "getHealth"
}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   132  100    62    222    104 --:--:-- --:--:-- --:--:--   327
{
  "jsonrpc": "2.0",
  "id": 10235,
  "result": {
    "status": "healthy",
    "latestLedger": 492795,
    "oldestLedger": 475516,
    "ledgerRetentionWindow": 17280
  }
}
```

**Comment by Roman-Liquify** [comment]
Correct. These are working public endpoints which require no platform login or any registration, so it's different to other providers on the list. 

Ideally if you can list them similarly to SDF format, that would make more sense, I've just followed the current format.

Would it make sense to put them under SDF's?

**Comment by Roman-Liquify** [comment]
Hi @mollykarcher , @ElliotFriend I don't see our endpoints on the page anymore, is there a better suggested format I can follow?

**Comment by briwylde08** [comment]
Fixed: https://github.com/stellar/stellar-docs/pull/822

**Comment by janewang** [comment]
@Roman-Liquify Hope you are well. I was wondering if you could whitelist lab.stellar.org.

We tried to input `https://stellar-mainnet.liquify.com/api=41EEWAH79Y5OCGI7/mainnet` in https://lab.stellar.org/ as a mainnet RPC but then saw that the requests are blocked by CORS. If you could whitelist the lab, it will make it much easier for developers to use your mainnet endpoint with Lab. 

Screenshot 2024-09-30 at 2 17 00 PM

Thank you for your attention!

**Comment by Roman-Liquify** [comment]
Hello @janewang , apologies for the delayed reply, we are currently resyncing the nodes and once added to the load balancer we'll fix the CORS issue. I'll update here once done

**Pull request merged**
