### PR TITLE
ANCHOR-688: Update flow diagrams

### PR DESCRIPTION
**Pull request by Ifropc**

### CODE REVIEW

**Comment by JakeUrban** [comment]
A couple things:

- the font sizing seems to be slightly off for some of the components, can we fix that?
- do we want to add sections of the integration guide explaining the on-hold flow?
- don't we want to add the same changes for SEP-6?

**Comment by JakeUrban** [comment]
The font sizing issue still appears to be there

**Comment by Ifropc** [comment]
Sorry Jake can you point it out which texts are differ? I can't see it...

**Comment by JakeUrban** [comment]
Its pretty minor, if its not straightforward to fix I think its fine.

Screenshot 2024-06-18 at 12 16 15 PM
Screenshot 2024-06-18 at 12 16 02 PM
Screenshot 2024-06-18 at 12 15 58 PM

**Comment by Ifropc** [comment]
It actually says it uses the same style
image
image

**Comment by JakeUrban** [comment]
Ok, lets move forward then, its not a big deal.

**Review by JakeUrban — APPROVED** [review]

**Pull request merged**
