### PR TITLE
fix nginx config.

### PR DESCRIPTION
**Pull request by overcat**
1. `location / { deny all; }` conflicts with the later defined `location / {...}` and I think it is unnecessary, we can remove it.
2. The usage of `try_files` is incorrect, we need to correct it. https://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

### CODE REVIEW

**Review by mwtzzz — CHANGES_REQUESTED** [review]
Please explain why you think `deny all` is unnecessary? And if it's interfering with another rule down below, then I think we should move it below that rule instead of eliminating it.

**Comment by overcat** [comment]
> Please explain why you think `deny all` is unnecessary? And if it's interfering with another rule down below, then I think we should move it below that rule instead of eliminating it.

Hi @mwtzzz, Nginx does not allow adding duplicate locations, so moving it below is not feasible. Instead, any files in the `/mnt/xvdf/stellar-core-archive/node_001/` folder are not private and can be made public.

**Comment by briwylde08** [comment]
Hi @mwtzzz! Are you okay reviewing this PR?

**Review by mwtzzz — APPROVED** [review]
LG

**Review by briwylde08 — APPROVED** [review]

**Comment by briwylde08** [comment]
Hi @overcat! Are you able to fix the conflict? Then we're good to merge!

**Comment by overcat** [comment]
> Hi @overcat! Are you able to fix the conflict? Then we're good to merge!

Hi @briwylde08, resolved.

**Pull request merged**
