### PR TITLE
Expand get transaction

### PR DESCRIPTION
**Pull request by Myestery**
Bounty Submission for https://github.com/stellar/stellar-docs/issues/621

@briwylde08

### CODE REVIEW

**Comment by briwylde08** [comment]
Thank you so much for your submission! We'll review and get back to you with any questions or an approval!

**Comment by Myestery** [comment]
> Thank you so much for your submission! We'll review and get back to you with any questions or an approval!

Okay

**Review by ElliotFriend — COMMENTED** [review]
Hi, @Myestery! Thanks for the contribution!

The Python and JS examples are great! The Go example is a little out of place, though, since it's a client to Horizon, rather than RPC. Let's remove it here.

**Comment by Myestery** [comment]
> Hi, @Myestery! Thanks for the contribution!
> 
> The Python and JS examples are great! The Go example is a little out of place, though, since it's a client to Horizon, rather than RPC. Let's remove it here.

I have replaced it with a Java SDK implementation

**Review by ElliotFriend — APPROVED** [review]
That's excellent! Looks good to me!

**Comment by briwylde08** [comment]
Hi @Myestery! Can you please comment in the corresponding issue so we can start the award process? Here is the issue: https://github.com/stellar/stellar-docs/issues/621

**Pull request merged**
