### PR TITLE
Fetching Data from Indexers and Integrating it to a frontend interface

### PR DESCRIPTION
**Pull request by Myestery**
@briwylde08 This is ready for review
Meant to close https://github.com/stellar/stellar-docs/issues/600

### CODE REVIEW

**Comment by briwylde08** [comment]
Thank you for your submission! We'll get it reviewed and let you know any feedback!

**Review by ElliotFriend — CHANGES_REQUESTED** [review]
Hi, @Myestery!! Thanks for submitting your work! I got a little bit into your submission, and I'm gonna pause here, and give a couple pieces of feedback that should be addressed before I get into the more nitty-gritty:

1. I think we should demo something besides events. Since we already have guides on both [ingesting](https://developers.stellar.org/docs/build/guides/events/ingest) and [consuming](https://developers.stellar.org/docs/build/guides/events/consume) smart contract events, we're better served here by a demonstration querying something else from the indexer.
2. Overall, we need more detail. This is a pretty important tutorial that will quite likely see a lot of use and traffic. In a few of your other submissions, we were asking for pretty sparse code "snippets" to demonstrate RPC queries. In this guide, you've taken a step outside of that "barebones" train of thought, but I think we need at least one more step, if that makes sense. With this kind of guide, we're wanting to explain _why_ we're creating the `EventDataFetcher` function (for example) in this specific way, not just showcasing the _how_. We do want both, for sure. I think this is especially needed in the "frontend integration" section.

I did add some comments along the way, and you're welcome to address them if you want. But, I think there are some bigger fish to fry before you get to those.

Thanks again! This looks like a really promising start.

**Comment by Myestery** [comment]
Hello @ElliotFriend 
I have updated the docs to follow your comments
Pls take a look

**Comment by briwylde08** [comment]
Hi @Myestery!

Firstly, I’d like to sincerely thank you for your contributions to the docs bounty. Your enthusiasm and interest in participating and being an engaged member of the community is appreciated and valued.

Regarding some of the PRs you’ve submitted: there are a couple of recurring issues with detail, thoroughness, and direction, particularly with this PR and the fee GUI tool: https://github.com/stellar/stellar-docs/pull/757 (I’ll provide specific feedback in that PR). Unfortunately, these PRs don’t meet the quality standards required to be approved and awarded for the bounty. With some of these more open-ended submission prompts, it's good to think about what would truly be helpful to developers building on Stellar.

Again, your ongoing enthusiasm and participation in the bounty are super valuable, and I want to encourage you to keep engaging with our ecosystem. To improve future contributions, I recommend viewing some other submissions we’ve received and approved, particularly this one on consuming previously ingested events: https://github.com/stellar/stellar-docs/pull/638.
It might also be beneficial to connect with members of our community who have previously succeeded in these bounties. Requesting a review from them or engaging in Discord before your next submission could provide valuable insights.

Thank you again for your contributions, and I look forward to seeing your future work. Please feel free to reach out if you have any questions.

**Comment by Myestery** [comment]
> Hi @Myestery!
> 
> Firstly, I’d like to sincerely thank you for your contributions to the docs bounty. Your enthusiasm and interest in participating and being an engaged member of the community is appreciated and valued.
> 
> Regarding some of the PRs you’ve submitted: there are a couple of recurring issues with detail, thoroughness, and direction, particularly with this PR and the fee GUI tool: #757 (I’ll provide specific feedback in that PR). Unfortunately, these PRs don’t meet the quality standards required to be approved and awarded for the bounty. With some of these more open-ended submission prompts, it's good to think about what would truly be helpful to developers building on Stellar.
> 
> Again, your ongoing enthusiasm and participation in the bounty are super valuable, and I want to encourage you to keep engaging with our ecosystem. To improve future contributions, I recommend viewing some other submissions we’ve received and approved, particularly this one on consuming previously ingested events: #638. It might also be beneficial to connect with members of our community who have previously succeeded in these bounties. Requesting a review from them or engaging in Discord before your next submission could provide valuable insights.
> 
> Thank you again for your contributions, and I look forward to seeing your future work. Please feel free to reach out if you have any questions.

I'll sit back and take a good review of those merged PRs for the next 24 hours.
I'll definitely improve my writing before asking for reviews again.
Thank you for your valuable insight.

**Comment by briwylde08** [comment]
Closing per feedback above.

**Pull request closed without merging**
