### PR TITLE
Guide for type conversions

### LINKED ISSUE #607: Create guides for working with type conversions (Address to BytesN, String to ScVal, etc.) in various programming languages
**Get awarded:** up to $500 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Introduction that includes what type conversions are and discusses different data types like Address, BytesN, ScVal, etc., and their roles
- Code examples of converting various types in whatever programming language you’re working with
- Example scenarios where these types of conversions are used

### PR DESCRIPTION
**Pull request by Mackenzie-OO7**
Closes #607 

A guide for performing type conversions in different programming languages.

### CODE REVIEW

**Comment by briwylde08** [comment]
Thank you for your contribution! We'll get it assigned and reviewed and let you know if we have any questions. FYI, we've given reviewers a couple of weeks to review submissions but we'll try to get to it sooner!

**Comment by briwylde08** [comment]
Hi @Mackenzie-OO7! Can you fix the conflicting files? Once you do we can get this merged and talk award information! Thank you!

**Comment by Mackenzie-OO7** [comment]
> Hi @Mackenzie-OO7! Can you fix the conflicting files? Once you do we can get this merged and talk award information! Thank you!

Fixed it!

**Comment by Mackenzie-OO7** [comment]
> Nicely done! This is a great addition to the how to guides!

Thank you😁😁

**Pull request merged**
